### PR TITLE
Updated the classifier code and detector code for calling the classifier

### PR DESCRIPTION
**Pull request by shrikondra**
I didn't pushed the models on github.
A folder called models need to created in CarND-Capstone/ros/src/tl_detector/light_classification

I have kept the models on my google drive
https://drive.google.com/open?id=1dFrr6IOXNRxNhUUe7UDlmoWjY4gmZ0LR

### CODE REVIEW

**Comment by dinoboy197** [comment]
> A folder called models need to created in CarND-Capstone/ros/src/tl_detector/light_classification

Would you mind adding a bit to the readme file about how to do this? Perhaps add a couple of commands that can be copied and pasted into a terminal do this? (ex: `mkdir ...`, `cd ...`, `wget ...`, etc).

**Comment by dinoboy197** [comment]
> I have kept the models on my google drive

Maybe these should be placed in our group's central google drive folder? https://drive.google.com/drive/folders/13CqDIlbU4wImzOfS4R_3AzWTdfOKPMoD

**Comment by edufford** [comment]
I copied the models to the main google drive too.  They are not so big so eventually I think we can add them to the Github repo directly, once we have the final models for submission.

**Comment by edufford** [comment]
@meenunat Can you combine this with your latest code and make a new PR that references this PR?  After that, we can close this one and merge yours.

**Comment by meenunat** [comment]
@edufford - My changes has been merged already to the master - we may need to revert the last change. I tried to checkout the branch committed by @shrikondra and did git pull - but it is pulling it from master rather than  shrikondra_tl_classifier_pass - can anyone tell me how do I do this ?

**Comment by edufford** [comment]
Yea, it’s better if you’re able to combine the classifier into the current master as a new branch.  Let me know if there are any issues doing it that way.  Thanks!

**Comment by edufford** [comment]
This code will be merged by PR #63, so this PR can be closed

**Pull request closed without merging**
