### PR TITLE
Faster acceleration from stopped

### PR DESCRIPTION
**Pull request by teeekay**
Changed so velocity on first waypoint when starting from stopped is set to 3.0 m/s instead of 1.0 m/s.  This reduces time to get to 2.0 m/s from about 1.8 s to 1.0 s.  Jerk and acceleration values remain within limits on simulator with this change.
Creeping speed is also increased to 1.5 m/s from 1.0 m/s.
Reduced number of consecutive traffic light signal identifications from 4 to 3 to cut status change time down by 0.1 secs.

### CODE REVIEW

**Comment by edufford** [comment]
Although the jerk and accel values on the sim are still within limits, increasing the initial waypoint velocity to 3.0 m/s causes the initial throttle apply to increase from 15% to ~45%.  For Carla and a typical real car, 45% throttle is a pretty aggressive launch so I think it may be better to stick with 1.0 or 1.5 m/s so the throttle P term doesn't shoot to such a large initial throttle apply.  I think Carla will get going faster off the line than the simulator anyway since the simulator doesn't seem to model the real car's torque response very well.

The creep speed change seems fine, and helps the car get to the first stop line a little earlier so it will have more time stopped at the red before it turns green again.

For reducing the classification threshold from 4 to 3, this is ok but slightly increases risk of false detections passing through.  Not sure if it's worth the 0.1 sec savings since we've still seen some sporadic false detections in the rosbag data so far.

**Comment by teeekay** [comment]
What! no "Ludicrous" mode on our car.... I'll run some tests while varying initial speed between 1.0 to 2.0 to see how throttle reacts, and then put in a new commit.

**Comment by teeekay** [comment]
I'll also look back at the site logs to check the light identification to see what level is appropriate.  3 is definitely good enough on the simulator.

**Comment by edufford** [comment]
Yea, considering the big response differences between the sim and Carla, I bet the Udacity driver has had a few “ludicrous mode” experiences from testing all the group submissions, but I hope ours is more toward “chill mode”!

**Comment by teeekay** [comment]
Moved it to starting up at first waypoint with 1.0 m/s and 1.0 m/s^2.  put back classification threshold to 4.

**Pull request merged**
